### ISSUE TITLE
小白求教 Software中的两个压缩包分别是什么？

### ISSUE THREAD

**Issue by AlainConnor** [Commander-bao/MiniTV-for-couples#2]
LoveTv2.0.zip
Software.zip

请问这俩有啥区别吗？ 应该编译哪个呢？ 

我是新入门的小白。。 辛苦大佬看下

**Comment by Commander-bao** [comment]
第一个是一代小电视的，第二个是二代小电视的

**Comment by Commander-bao** [comment]
LoveTV2.0是二代小电视的，Software是一代小电视的
